package uk.telecom.o2c.delegate;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.springframework.stereotype.Component;
import uk.telecom.o2c.domain.Dispute;
import uk.telecom.o2c.repository.DisputeRepository;

@Component("rootCauseAnalysisDelegate")
@RequiredArgsConstructor
@Slf4j
public class RootCauseAnalysisDelegate implements JavaDelegate {

    private final DisputeRepository disputeRepository;

    @Override
    public void execute(DelegateExecution execution) throws Exception {
        String disputeId = (String) execution.getVariable("disputeId");
        log.info("Root cause analysis for dispute: {}", disputeId);

        Dispute dispute = disputeRepository.findByDisputeId(disputeId)
                .orElseThrow(() -> new RuntimeException("Dispute not found: " + disputeId));

        String rootCause = switch (dispute.getCategory()) {
            case BILLING_ERROR      -> "Rating engine applied incorrect tariff — CDR re-rating required";
            case DUPLICATE_CHARGE   -> "Duplicate invoice generated by billing cycle overlap";
            case SERVICE_NOT_RECEIVED -> "Provisioning failure — service activation not completed";
            default                 -> "Manual investigation required";
        };

        dispute.setRootCause(rootCause);
        dispute.setStatus(Dispute.DisputeStatus.RESOLVED);
        disputeRepository.save(dispute);

        execution.setVariable("rootCause", rootCause);
        log.info("RCA complete for dispute {}: {}", disputeId, rootCause);
    }
}
